{
 "title": "Kaizenizer",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "counters_segment",
    "label": "Counters segment",
    "query": "SELECT DISTINCT segment FROM metrics WHERE name LIKE 'counter/%';"
   }
  ]
 },
 "panels": [
  {
   "title": "Lead and Cycle Time - Rolling average",
   "type": "graph",
   "description": "Lead and Cycle Time, rolling average over 10 and 100 issues",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  AVG(value)\n    OVER (ORDER BY time ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS lead_short\nFROM\n  metrics\nWHERE\n  $__timeFilter(time)\nAND name = 'lead_time'"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  AVG(value)\n    OVER (ORDER BY time ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) AS cycle_short\nFROM\n  metrics\nWHERE\n  $__timeFilter(time)\nAND name = 'cycle_time'"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  AVG(value)\n    OVER (ORDER BY time ROWS BETWEEN 10 PRECEDING AND CURRENT ROW) AS lead_long\nFROM\n  metrics\nWHERE\n  $__timeFilter(time)\nAND name = 'lead_time'"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  AVG(value)\n    OVER (ORDER BY time ROWS BETWEEN 10 PRECEDING AND CURRENT ROW) AS cycle_long\nFROM\n  metrics\nWHERE\n  $__timeFilter(time)\nAND name = 'cycle_time'"
    }
   ]
  },
  {
   "title": "Cumulative Flow Diagram",
   "type": "graph",
   "description": "Number of Jira issues in Backlog (Open, Todo, Backlog...) and WIP statuses (In Development, In Review, Ready for Release...)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS backlog\nFROM\n  metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/cfd_backlog'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS wip\nFROM\n  metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/cfd_wip'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "WIP composition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS product\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/wip_product'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS bug\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/wip_bug'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS ops\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/wip_ops'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS technical\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/wip_technical'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Backlog composition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS product\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/backlog_product'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS bug\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/backlog_bug'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS ops\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/backlog_ops'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(time),\n  SUM(value) AS technical\nFROM metrics\nWHERE $__timeFilter(time)\nAND name = 'counter/backlog_technical'\nAND segment IN ($counters_segment)\nGROUP BY time\nORDER BY time ASC"
    }
   ]
  }
 ]
}